### ISSUE TITLE
Sitemap 无法在此版本的typecho下正常工作

### ISSUE THREAD

**Issue by zhuwenbing** [RainshawGao/Typecho-Plugin-Sitemap#1]
Sitemap 版本 2.0.1
Typecho 版本 1.2.0（开发版最新代码）

**Comment by Rainshaw** [comment]
我能用呀。。。就是用的最新的代码呀

**Comment by zhuwenbing** [comment]
刚刚又拉了一遍typecho的代码还是一样，如下图所示：
[截图](https://ki.readyspace.io/chevereto/images/2021/09/06/screenshot.png)

**Comment by Rainshaw** [comment]
fix in d44499e2d2782ca95d0a2162144980aaba63b3a4
