### ISSUE TITLE
请问生成的sitemap如何查看？

### ISSUE THREAD

**Issue by Doubeecat** [RainshawGao/Typecho-Plugin-Sitemap#2]

**Comment by Rainshaw** [comment]
启用后，访问 /sitemap.xml

**Comment by Doubeecat** [comment]
> 启用后，访问 /sitemap.xml

似乎并没有？我在后台启用了插件并且也给了权限，您可以试着访问下 [link](https://www.doubeecat.xyz/sitemap.xml)

**Comment by Rainshaw** [comment]
https://www.doubeecat.xyz/index.php/sitemap.xml

你没配置伪静态

**Comment by Doubeecat** [comment]
> https://www.doubeecat.xyz/index.php/sitemap.xml
> 
> 你没配置伪静态

谢谢orz
